# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos8"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./playbook.yaml"
    ansible.host_vars = {
      "ansible_python_interpreter" => "/usr/libexec/platform-python"
    }
  end

  config.vm.network "forwarded_port", guest: 8043, host: 8043

  config.vm.synced_folder "/Users/luizcosta", "/vagrant", disabled: false
end
